name: Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '14']
    name: Node ${{ matrix.node }} sample
    steps:
      - uses: actions/checkout@v2
      - run: git config --global user.email "ericktijerou@gmail.com"
      - run: git config --global user.name "Erick Tijero"
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm run build
      - run: npm run deploy

